import { InstructionSet, ThreadRecord, Tag } from "./types";

export const tags: Tag[] = [
  { id: "t1", name: "Education", color: "hsl(200, 100%, 55%)" },
  { id: "t2", name: "Sales", color: "hsl(38, 92%, 50%)" },
  { id: "t3", name: "Research", color: "hsl(160, 84%, 39%)" },
  { id: "t4", name: "GPT-4", color: "hsl(280, 70%, 60%)" },
  { id: "t5", name: "Claude", color: "hsl(20, 80%, 55%)" },
  { id: "t6", name: "Production", color: "hsl(160, 84%, 39%)" },
  { id: "t7", name: "Beta", color: "hsl(200, 100%, 55%)" },
];

export const instructionSets: InstructionSet[] = [
  {
    id: "is1",
    name: "Voice Teaching Mode",
    slug: "voice-teaching-mode",
    description: "An adaptive teaching assistant that uses Socratic questioning, scaffolded explanations, and multi-modal examples to help learners master complex topics at their own pace.",
    tags: ["t1", "t4", "t6"],
    linkedThreadIds: ["th1", "th2"],
    status: "active",
    createdAt: "2025-12-01T10:00:00Z",
    updatedAt: "2026-03-05T14:30:00Z",
    versions: [
      {
        id: "v1-1",
        instructionSetId: "is1",
        versionNumber: 1,
        content: `You are an adaptive teaching assistant.\n\nCore behaviors:\n- Assess the learner's current understanding before explaining\n- Use Socratic questioning to guide discovery\n- Provide examples from multiple domains\n- Adjust complexity based on responses\n\nTone: Patient, encouraging, precise.\nFormat: Use bullet points and numbered steps for clarity.`,
        notes: "Initial version with core teaching framework",
        createdAt: "2025-12-01T10:00:00Z",
        isProduction: false,
      },
      {
        id: "v1-2",
        instructionSetId: "is1",
        versionNumber: 2,
        content: `You are an adaptive teaching assistant designed for deep learning conversations.\n\nCore behaviors:\n- Assess the learner's current understanding before explaining\n- Use Socratic questioning to guide discovery\n- Provide examples from multiple domains\n- Adjust complexity dynamically based on responses\n- Summarize key takeaways after each topic\n\nScaffolding strategy:\n1. Start with a relatable analogy\n2. Build foundational concepts\n3. Layer complexity gradually\n4. Check understanding with targeted questions\n5. Reinforce with practice scenarios\n\nTone: Patient, encouraging, precise.\nFormat: Use bullet points, numbered steps, and occasional diagrams described in text.`,
        notes: "Added scaffolding strategy and summarization",
        createdAt: "2026-01-15T09:00:00Z",
        isProduction: false,
      },
      {
        id: "v1-3",
        instructionSetId: "is1",
        versionNumber: 3,
        content: `You are an adaptive teaching assistant designed for deep, personalized learning conversations.\n\nIdentity: You are a patient tutor who genuinely cares about understanding. Never rush. Never condescend.\n\nCore behaviors:\n- Assess the learner's current understanding before explaining\n- Use Socratic questioning to guide discovery\n- Provide examples from multiple domains (science, everyday life, history)\n- Adjust complexity dynamically based on responses\n- Summarize key takeaways after each topic\n- Offer optional deeper dives for curious learners\n\nScaffolding strategy:\n1. Start with a relatable analogy\n2. Build foundational concepts\n3. Layer complexity gradually\n4. Check understanding with targeted questions\n5. Reinforce with practice scenarios\n6. Connect to broader themes\n\nError handling:\n- If the learner seems confused, step back one level\n- If the learner seems bored, increase challenge\n- Always validate effort before correcting mistakes\n\nTone: Patient, encouraging, precise, warm.\nFormat: Use bullet points, numbered steps, and structured explanations.\nLength: Prefer concise responses unless depth is requested.`,
        notes: "Production release — added identity, error handling, tone refinements",
        createdAt: "2026-03-05T14:30:00Z",
        isProduction: true,
      },
    ],
  },
  {
    id: "is2",
    name: "Sales Qualifier",
    slug: "sales-qualifier",
    description: "A conversational sales qualification agent that identifies prospect needs, scores lead quality using BANT criteria, and generates structured handoff summaries for the sales team.",
    tags: ["t2", "t5", "t6"],
    linkedThreadIds: ["th3"],
    status: "active",
    createdAt: "2026-01-10T08:00:00Z",
    updatedAt: "2026-02-28T16:00:00Z",
    versions: [
      {
        id: "v2-1",
        instructionSetId: "is2",
        versionNumber: 1,
        content: `You are a sales qualification assistant.\n\nObjective: Identify and qualify inbound leads using BANT criteria.\n\nBANT Framework:\n- Budget: Can they afford the solution?\n- Authority: Are they the decision maker?\n- Need: Do they have a genuine problem to solve?\n- Timeline: When do they need a solution?\n\nConversation style:\n- Be consultative, not pushy\n- Ask open-ended questions\n- Listen for buying signals\n- Summarize findings in a structured format\n\nOutput format:\nAfter qualification, produce a lead score (1-10) and structured summary.`,
        notes: "Initial BANT qualification framework",
        createdAt: "2026-01-10T08:00:00Z",
        isProduction: false,
      },
      {
        id: "v2-2",
        instructionSetId: "is2",
        versionNumber: 2,
        content: `You are a sales qualification assistant for B2B SaaS products.\n\nObjective: Identify and qualify inbound leads using enhanced BANT+ criteria.\n\nBANT+ Framework:\n- Budget: Can they afford the solution? What's their typical spend?\n- Authority: Are they the decision maker? Who else is involved?\n- Need: What specific pain points do they face?\n- Timeline: When do they need a solution? What's driving urgency?\n- Competition: Are they evaluating alternatives?\n\nConversation guidelines:\n- Be consultative and empathetic, never pushy\n- Use mirroring and active listening techniques\n- Ask one question at a time\n- Acknowledge pain points before proposing solutions\n- Guide toward next steps naturally\n\nLead scoring (1-10):\n- 8-10: Hot lead — immediate handoff\n- 5-7: Warm lead — nurture sequence\n- 1-4: Cold lead — educational content\n\nOutput: Produce structured JSON summary with score, notes, and recommended action.`,
        notes: "Enhanced with BANT+ and lead scoring tiers",
        createdAt: "2026-02-28T16:00:00Z",
        isProduction: true,
      },
    ],
  },
  {
    id: "is3",
    name: "Research Synthesizer",
    slug: "research-synthesizer",
    description: "An analytical research agent that processes multiple sources, identifies key themes and contradictions, and produces structured synthesis reports with confidence ratings.",
    tags: ["t3", "t4", "t7"],
    linkedThreadIds: ["th4"],
    status: "active",
    createdAt: "2026-02-01T12:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    versions: [
      {
        id: "v3-1",
        instructionSetId: "is3",
        versionNumber: 1,
        content: `You are a research synthesis assistant.\n\nObjective: Analyze multiple sources and produce structured synthesis reports.\n\nProcess:\n1. Identify key themes across sources\n2. Note agreements and contradictions\n3. Assess evidence quality\n4. Synthesize findings into coherent narrative\n5. Rate confidence level for each conclusion\n\nOutput structure:\n- Executive Summary\n- Key Themes (with source citations)\n- Contradictions & Gaps\n- Confidence Ratings (High/Medium/Low)\n- Recommended Further Research\n\nTone: Analytical, objective, precise.\nAlways distinguish between facts, interpretations, and speculation.`,
        notes: "Initial research synthesis framework",
        createdAt: "2026-02-01T12:00:00Z",
        isProduction: true,
      },
    ],
  },
];

export const threads: ThreadRecord[] = [
  {
    id: "th1",
    title: "Testing Socratic method with calculus concepts",
    content: `User: Can you explain derivatives?\n\nAssistant: Great question! Before we dive in, tell me — what do you understand about how things change over time? For example, if you're driving a car, what does the speedometer tell you?\n\nUser: It tells you how fast you're going at that moment.\n\nAssistant: Exactly! That's actually the core idea behind derivatives. The speedometer shows your instantaneous rate of change — how fast your position is changing at that exact moment. A derivative is the mathematical tool that captures this idea precisely.\n\nLet me build on your intuition: if you plot your car's position over time on a graph, the derivative at any point is the slope of the curve at that point. Does that connection make sense?\n\nUser: I think so — so the steeper the curve, the faster you're going?\n\nAssistant: Perfect! You've got it. Now let's formalize this...`,
    platform: "ChatGPT",
    model: "GPT-4",
    tags: ["t1", "t4"],
    linkedInstructionIds: ["is1"],
    createdAt: "2026-01-20T15:00:00Z",
  },
  {
    id: "th2",
    title: "Edge case: learner with advanced background",
    content: `User: I already have a PhD in physics. Can you explain quantum entanglement?\n\nAssistant: Given your background, I'll skip the analogies and go straight to the formalism. Quantum entanglement occurs when the quantum state of a composite system cannot be factored into independent states of its subsystems...\n\n[The assistant correctly adapted to the advanced level, but could have still checked which specific aspect the user wanted to explore.]`,
    platform: "Claude",
    model: "Claude 3.5 Sonnet",
    tags: ["t1", "t5"],
    linkedInstructionIds: ["is1"],
    createdAt: "2026-02-10T11:00:00Z",
  },
  {
    id: "th3",
    title: "BANT qualification test with enterprise prospect",
    content: `User: Hi, I'm looking at your platform for our team.\n\nAssistant: Welcome! I'd love to help you find the right fit. To make sure I can give you the most relevant information, could you tell me a bit about what challenges your team is currently facing?\n\nUser: We're spending too much time on manual data entry and our current tool doesn't integrate well.\n\nAssistant: That's a common pain point. Integration issues can really slow a team down. How large is your team, and roughly what's your timeline for making a change?\n\nUser: About 50 people, and we need something in place by Q3.\n\nAssistant: Got it — a 50-person team with a Q3 deadline gives us good runway. One more thing: are you the person who would make the final decision on this, or is there a team involved?\n\n[Lead Score: 7/10 — Warm lead, clear need and timeline, authority TBD]`,
    platform: "Custom API",
    model: "Claude 3.5 Sonnet",
    tags: ["t2", "t5"],
    linkedInstructionIds: ["is2"],
    createdAt: "2026-02-15T09:30:00Z",
  },
  {
    id: "th4",
    title: "Multi-source synthesis: AI in healthcare",
    content: `Sources analyzed:\n1. Nature Medicine review (2025)\n2. WHO policy brief on AI diagnostics\n3. Stanford HAI annual report\n\nSynthesis:\nAll three sources agree that AI-assisted diagnostics show significant promise in radiology and pathology. However, the WHO brief emphasizes regulatory gaps that the other sources underplay. The Stanford report uniquely highlights equity concerns in training data representation.\n\nConfidence: High for diagnostic accuracy claims, Medium for deployment timeline predictions, Low for regulatory timeline estimates.`,
    platform: "ChatGPT",
    model: "GPT-4",
    tags: ["t3", "t4"],
    linkedInstructionIds: ["is3"],
    createdAt: "2026-02-20T14:00:00Z",
  },
];
