// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-groups.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_groups_default = defineTool({
  name: "list_groups",
  title: "List Groups",
  description: "List all top-level instruction groups (categories) belonging to the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("categories").select("id, name, description, color, created_at, updated_at").order("created_at", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { groups: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-instructions.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_instructions_default = defineTool2({
  name: "list_instructions",
  title: "List Instructions",
  description: "List instruction sets (formerly 'groups') for the signed-in user. Optionally filter by category (group).",
  inputSchema: {
    category_id: z.string().uuid().optional().describe("Optional UUID of a top-level group to filter by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser2(ctx).from("instruction_groups").select("id, name, description, color, category_id, created_at, updated_at").order("updated_at", { ascending: false });
    if (category_id) query = query.eq("category_id", category_id);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { instructions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-production-instruction.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_production_instruction_default = defineTool3({
  name: "get_production_instruction",
  title: "Get Production Instruction",
  description: "Fetch the current production version of an instruction set. Returns the full instruction content ready to paste into an AI system prompt.",
  inputSchema: {
    instruction_id: z2.string().uuid().describe("UUID of the instruction set.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ instruction_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const client = supabaseForUser3(ctx);
    const { data: group, error: gErr } = await client.from("instruction_groups").select("id, name, description").eq("id", instruction_id).single();
    if (gErr || !group) {
      return { content: [{ type: "text", text: gErr?.message ?? "Instruction not found" }], isError: true };
    }
    const { data: version, error: vErr } = await client.from("instruction_versions").select("id, version_number, content, notes, created_at").eq("group_id", instruction_id).eq("is_production", true).maybeSingle();
    if (vErr) return { content: [{ type: "text", text: vErr.message }], isError: true };
    if (!version) {
      return { content: [{ type: "text", text: `No production version set for "${group.name}".` }], isError: true };
    }
    const payload = { instruction: group, production: version };
    return {
      content: [
        { type: "text", text: `# ${group.name} (v${version.version_number})

${version.content}` }
      ],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-threads.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_threads_default = defineTool4({
  name: "list_threads",
  title: "List Threads",
  description: "List conversation threads for the signed-in user. Filter by instruction_id or rating (positive/neutral/negative).",
  inputSchema: {
    instruction_id: z3.string().uuid().optional().describe("Optional instruction (group) UUID to filter by."),
    rating: z3.enum(["positive", "neutral", "negative"]).optional().describe("Optional rating filter."),
    limit: z3.number().int().min(1).max(100).default(20).describe("Maximum threads to return (1-100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ instruction_id, rating, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let query = supabaseForUser4(ctx).from("threads").select("id, title, platform, model, rating, group_id, created_at").order("created_at", { ascending: false }).limit(limit);
    if (instruction_id) query = query.eq("group_id", instruction_id);
    if (rating) query = query.eq("rating", rating);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { threads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-thread.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function cleanThread(raw) {
  return raw.replace(/\r\n/g, "\n").replace(/\n{3,}/g, "\n\n").replace(/^\s*(Copy|Share|Edit|Regenerate|Continue|Send)\s*$/gim, "").replace(/^\s*\d+\s*\/\s*\d+\s*$/gm, "").trim();
}
var create_thread_default = defineTool5({
  name: "create_thread",
  title: "Save Thread",
  description: "Save a conversation thread. The raw content is auto-cleaned. Optionally link to an instruction set.",
  inputSchema: {
    title: z4.string().min(1).max(200).describe("Short descriptive title."),
    content: z4.string().min(1).describe("Raw pasted thread content (will be auto-cleaned)."),
    instruction_id: z4.string().uuid().optional().describe("Optional instruction (group) UUID to link this thread to."),
    platform: z4.string().max(50).optional().describe("Platform name (e.g. ChatGPT, Claude, Cursor)."),
    model: z4.string().max(50).optional().describe("Model name (e.g. gpt-5, claude-sonnet-4)."),
    rating: z4.enum(["positive", "neutral", "negative"]).optional().describe("Optional initial rating.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ title, content, instruction_id, platform, model, rating }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const cleaned = cleanThread(content);
    const insert = {
      user_id: ctx.getUserId(),
      title,
      raw_content: content,
      cleaned_content: cleaned,
      platform: platform ?? "",
      model: model ?? "",
      group_id: instruction_id ?? null,
      rating: rating ?? null
    };
    const { data, error } = await supabaseForUser5(ctx).from("threads").insert(insert).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved thread "${data.title}" (id: ${data.id}).` }],
      structuredContent: { thread: data }
    };
  }
});

// src/lib/mcp/tools/add-thread-comment.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var add_thread_comment_default = defineTool6({
  name: "add_thread_comment",
  title: "Add Thread Comment",
  description: "Add a comment or learning note to an existing thread.",
  inputSchema: {
    thread_id: z5.string().uuid().describe("UUID of the thread."),
    content: z5.string().min(1).max(2e3).describe("Comment text.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ thread_id, content }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser6(ctx).from("thread_comments").insert({ thread_id, content, user_id: ctx.getUserId() }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Comment added to thread ${thread_id}.` }],
      structuredContent: { comment: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "avttfayhcbfrglyxybgp";
var mcp_default = defineMcp({
  name: "instruction-os-mcp",
  title: "Instruction OS",
  version: "0.1.0",
  instructions: "Instruction OS lets you manage versioned AI custom instructions organized into Groups (top-level categories like Developing, Creative) and Instructions (specific personas like Tech Lead, Art Director). Use `list_groups` and `list_instructions` to explore the user's setup, `get_production_instruction` to fetch the current instruction content ready to paste into an AI system prompt, and `list_threads` / `create_thread` / `add_thread_comment` to save and review conversation threads that inform instruction improvements.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_groups_default,
    list_instructions_default,
    get_production_instruction_default,
    list_threads_default,
    create_thread_default,
    add_thread_comment_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
